AWSTemplateFormatVersion: '2010-09-09'
Description: "flows pdf"
Resources:
  extracttextFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code: extracttext
      Handler: index.handler
      Role:
        Fn::GetAtt: [ LambdaRole , Arn ]
      Runtime: nodejs8.10
      Timeout: 300
  extracttextLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${extracttextFunction}"
      RetentionInDays: 7
  converttopngFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code: converttopng
      Handler: index.handler
      Role:
        Fn::GetAtt: [ LambdaRole , Arn ]
      Runtime: nodejs8.10
      Timeout: 300
      MemorySize: 512
  converttopngLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${converttopngFunction}"
      RetentionInDays: 7
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: LambdaRolePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - logs:CreateLogStream
              - logs:PutLogEvents
              Resource: arn:aws:logs:*:*:*
  InvokeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            AWS:
            - 321232316075
            - 184705290838
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: LambdaRolePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - lambda:InvokeFunction
              Resource:
              - Fn::GetAtt: [ extracttextFunction , Arn ]
              - Fn::GetAtt: [ converttopngFunction , Arn ]
Outputs:
  extracttextFunction:
    Description: 'extracttext'
    Value:
      Fn::GetAtt: [ extracttextFunction , Arn ]
  extracttextRole:
    Description: 'extracttext'
    Value:
      Fn::GetAtt: [ InvokeRole , Arn ]
  converttopngFunction:
    Description: 'converttopng'
    Value:
      Fn::GetAtt: [ converttopngFunction , Arn ]
  converttopngRole:
    Description: 'converttopng'
    Value:
      Fn::GetAtt: [ InvokeRole , Arn ]
